---
- name: Install nftables
  ansible.builtin.package:
    name: nftables
    state: present
  tags:
    - role::nftables

- name: Enable nftables
  ansible.builtin.service:
    name: nftables
    enabled: true
  tags:
    - role::nftables

- name: Template nftables configuration
  ansible.builtin.copy:
    content: |
      #!/usr/sbin/nft -f

      {{ nftables_configuration }}
    dest: /etc/nftables.conf
    owner: root
    group: root
    mode: "0544"
    validate: /usr/sbin/nft --check --file %s
  notify:
    - Reload nftables
  tags:
    - role::nftables
